### ISSUE TITLE
Allow changing image loading implementation

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/pntr#126]
Add ` PNTR_LOAD_IMAGE` define to allow changing how images are loaded. Similar to `PNTR_LOAD_FILE`

**Comment by konsumer** [comment]
An example is like emscritpen, where you could leverage the browser's image parser:

- new `Image()` for filedata (bytes can pushed into `URL.createObjectURL()` with a `Blob`)
- draw image to `OffscreenCanvas`
- get pixel data into `Uint8Array`
- copy pixels into wasm memory
- revoke the objectURL & delete the image to clear the mem
 
it uses an async callback though, (on image load) so it could require other stuff (ASYNCIFY, etc.)
