### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/pntr#39]
![pntr](https://user-images.githubusercontent.com/25086/215878688-821ef1f4-47f4-4072-83c9-b0d0da0a21ab.png)

**Comment by RobLoach** [comment]
![pntr](https://user-images.githubusercontent.com/25086/215881200-0560d575-0c59-49ec-9bec-bf78a8b41128.png)

By [MrRavenist](https://www.reddit.com/user/MrRavenist).

**Comment by konsumer** [comment]
OMG, I love this.
